[package]
name = "danger-rs"
version = "0.1.0"
description = "Automate your code review process with Rust"
edition = "2021"
license = "MIT"
repository = "https://github.com/tamasmagyar/danger-rs"
readme = "README.md"
keywords = ["code-review", "ci", "automation", "danger"]
categories = ["development-tools"]

[dependencies]